; ######################################################################################################################################################################################################
;Code below was generated by: 'File to Base64 String' Code Generator v1.20 Build 2015-01-20

Func _Full_greenico($bSaveBinary = False, $sSavePath = @ScriptDir)
	Local $Full_greenico
	$Full_greenico &= 'uLEAAAABAAYAEBACEABwBAAoAQAAQGYAAAAYGAN46CUAeI4ADCAgBDwCAIAAdgMAADAwAzwgaAYAAF4ABkBAQQQeCgAAxgwAgAAFAx6UAF4uFwAAKN8CIgCOAAYBLhYA/xca4QD1gZMYgAEw/5M/AD8APwDvPwA/ANR5wcJA/3k/AB8A/x8AHwAfAB8AHwAfAB8AHwD/HwAfAB8AHwAfAB8AHwAfAPv6XGGZYP9cHwAfAB8AHwD/HwAfAB8AHwAfAB8AHwAfAP8PAA8ADwAPAA8ADwAPAA8A/w8ADwAPAA8ADwAPAA8ADwD/DwAPAA8ADwAPAA8ADwAPAP8PAA8ADwAPAA8ADwAPAA8A/w8ADwAPAA8ADwAPAA8ADwD/DwAPAA8ADwAPAA8ADwAPAP8PAA8ADwAPAA8ADwAPAA8A/w8ADwAPAA8ADwAPAA8ADwDvDwAPAHJmsZSAf2Z/Zg8A/w8ADwAPAA8ADwAPAA8ADwD/DwAPAA8ADwAPAA8ADwAPAP8PAA8ADwAPAA8ADwAPAA8A/w8ADwAPAA8ADwAPAA8ADwD/DwAPAA8ADwAPAA8ADwAPAAcPAA8ABACosAIAKgeJUE5HDQoEGgpAAQ1JSERSCAAAAUABAQAIBgHAAFxyqGYAAAIAW0lEQVR42u0E1DFgAwjDsIF/AM9gAAckEnq0ADKZAC+1BGAAgIABAAYAGAAfAf8fAQEBvwQfAS8FzwGPAI8A/48ALwWPAI8AjwCPAD8BjwD/jwCPAC8FzwGPAI8AjwAvBQ+PAI8AjwCEAHBZrPdAA/5gevaDsShJAEVORK5CYII='
	$Full_greenico = _WinAPI_Base64Decode($Full_greenico)
	Local $tSource = DllStructCreate('byte[' & BinaryLen($Full_greenico) & ']')
	DllStructSetData($tSource, 1, $Full_greenico)
	Local $tDecompress
	_WinAPI_LZNTDecompress($tSource, $tDecompress, 6594)
	$tSource = 0
	Local Const $bString = Binary(DllStructGetData($tDecompress, 1))
	If $bSaveBinary Then
		Local Const $hFile = FileOpen($sSavePath & "\Full_green.ico", 18)
		If @error Then Return SetError(1, 0, 0)
		FileWrite($hFile, $bString)
		FileClose($hFile)
	EndIf
	Return $bString
EndFunc   ;==>_Full_greenico

Func _Full_greyico($bSaveBinary = False, $sSavePath = @ScriptDir)
	Local $Full_greyico
	$Full_greyico &= 'urEAAAABAAYAEBACEABwBAAoAQAAQGYAAAAYGAN46CUAeI4ADCAgBDwCAIAAdgMAADAwAzwgaAYAAF4ABkBAQQQeCgAAxgwAgAAFAx6WAF4uFwAAKB8CIgCOAAYBLhUAwMDA1xYb4QCBkxiAATD/kz8Avz8APwA/AD8A1HnBwkD/ef8/AB8AHwAfAB8AHwAfAB8A/x8AHwAfAB8AHwAfAB8AHwDvHwAfAPpcYZlg/1yfCR8A/x8AHwAfAB8AHwAfAB8AHwD/HwAfAA8ADwAPAA8ADwAPAP8PAA8ADwAPAA8ADwAPAA8A/w8ADwAPAA8ADwAPAA8ADwD/DwAPAA8ADwAPAA8ADwAPAP8PAA8ADwAPAA8ADwAPAA8A/w8ADwAPAA8ADwAPAA8ADwD/DwAPAA8ADwAPAA8ADwAPAP8PAA8ADwAPAA8ADwAPAA8Avw8ADwAPAA8AcmaxlIB/Zv9/Zg8ADwAPAA8ADwAPAA8A/w8ADwAPAA8ADwAPAA8ADwD/DwAPAA8ADwAPAA8ADwAPAP8PAA8ADwAPAA8ADwAPAA8A/w8ADwAPAA8ADwAPAA8ADwAfDwAPAA8ADwAEAKywAgAqB4lQTkcNCgQaCkABDUlIRFIIAAABQAEBAAgGAcAAXHKoZgAAAgBdSURBVHja7QDUQQEAMAjEsAAx/6LOGRjAAQCJhD5aSfoBJwB9CcAAAAMADPgAMAAfAR8BAQG/BB8B/y8FzwGPAI8AjwAvBY8AjwD/jwCPAD8BjwCPAI8ALwXPAf+PAI8AjwAvBY8AjwCPAIQAAGAzNs8FP9q5BOTI0ShJRU5ErgBCYII='
	$Full_greyico = _WinAPI_Base64Decode($Full_greyico)
	Local $tSource = DllStructCreate('byte[' & BinaryLen($Full_greyico) & ']')
	DllStructSetData($tSource, 1, $Full_greyico)
	Local $tDecompress
	_WinAPI_LZNTDecompress($tSource, $tDecompress, 6596)
	$tSource = 0
	Local Const $bString = Binary(DllStructGetData($tDecompress, 1))
	If $bSaveBinary Then
		Local Const $hFile = FileOpen($sSavePath & "\Full_grey.ico", 18)
		If @error Then Return SetError(1, 0, 0)
		FileWrite($hFile, $bString)
		FileClose($hFile)
	EndIf
	Return $bString
EndFunc   ;==>_Full_greyico

Func _Full_lightblueico($bSaveBinary = False, $sSavePath = @ScriptDir)
	Local $Full_lightblueico
	$Full_lightblueico &= 'ubEAAAABAAYAEBACEABwBAAoAQAAQGYAAAAYGAN46CUAeI4ADCAgBDwCAIAAdgMAADAwAzwgaAYAAF4ABkBAQQQeCgAAxgwAgAAFAx6UAF4uFwAAKJ8CIgCOAAYBLhUA//8WGuviAIGTGIABMP+TPwA/AN8/AD8APwDUecHCQP95PwD/HwAfAB8AHwAfAB8AHwAfAP8fAB8AHwAfAB8AHwAfAB8A9x8A+lxhmWD/XB8AHwAfAP8fAB8AHwAfAB8AHwAfAB8A/x8ADwAPAA8ADwAPAA8ADwD/DwAPAA8ADwAPAA8ADwAPAP8PAA8ADwAPAA8ADwAPAA8A/w8ADwAPAA8ADwAPAA8ADwD/DwAPAA8ADwAPAA8ADwAPAP8PAA8ADwAPAA8ADwAPAA8A/w8ADwAPAA8ADwAPAA8ADwD/DwAPAA8ADwAPAA8ADwAPAN8PAA8ADwByZrGUgH9mf2b/DwAPAA8ADwAPAA8ADwAPAP8PAA8ADwAPAA8ADwAPAA8A/w8ADwAPAA8ADwAPAA8ADwD/DwAPAA8ADwAPAA8ADwAPAP8PAA8ADwAPAA8ADwAPAA8ADw8ADwAPAAQAqLACACoHiVBORw0KBBoKQAENSUhEUggAAAFAAQEACAYBwABccqhmAAACAFtJREFUeNrtBNQxYAMIwzDAvwDnYQAHJBJ6tAArSQEvjQRgAICAAQAGABgAHwH/HwEBAb8EHwEvBc8BjwCPAP+PAC8FjwCPAI8AjwA/AY8A/48AjwAvBc8BjwCPAI8ALwUPjwCPAI8AhABwWeTNQAT9Rf0/XLEoSQBFTkSuQmCC'
	$Full_lightblueico = _WinAPI_Base64Decode($Full_lightblueico)
	Local $tSource = DllStructCreate('byte[' & BinaryLen($Full_lightblueico) & ']')
	DllStructSetData($tSource, 1, $Full_lightblueico)
	Local $tDecompress
	_WinAPI_LZNTDecompress($tSource, $tDecompress, 6594)
	$tSource = 0
	Local Const $bString = Binary(DllStructGetData($tDecompress, 1))
	If $bSaveBinary Then
		Local Const $hFile = FileOpen($sSavePath & "\Full_lightblue.ico", 18)
		If @error Then Return SetError(1, 0, 0)
		FileWrite($hFile, $bString)
		FileClose($hFile)
	EndIf
	Return $bString
EndFunc   ;==>_Full_lightblueico

Func _Full_redico($bSaveBinary = False, $sSavePath = @ScriptDir)
	Local $Full_redico
	$Full_redico &= 'uLEAAAABAAYAEBACEABwBAAoAQAAQGYAAAAYGAN46CUAeI4ADCAgBDwCAIAAdgMAADAwAzwgaAYAAF4ABkBAQQQeCgAAxgwAgAAFAx6UAF4uFwAAKN8CIgCOAAYBLhcA/xgb3wD1gZMYgAEw/5M/AD8APwDvPwA/ANR5wcJA/3k/AB8A/x8AHwAfAB8AHwAfAB8AHwD/HwAfAB8AHwAfAB8AHwAfAPv6XGGZYP9cnwkfAB8AHwD/HwAfAB8AHwAfAB8AHwAfAP8PAA8ADwAPAA8ADwAPAA8A/w8ADwAPAA8ADwAPAA8ADwD/DwAPAA8ADwAPAA8ADwAPAP8PAA8ADwAPAA8ADwAPAA8A/w8ADwAPAA8ADwAPAA8ADwD/DwAPAA8ADwAPAA8ADwAPAP8PAA8ADwAPAA8ADwAPAA8A/w8ADwAPAA8ADwAPAA8ADwDvDwAPAHJmsZSAf2Z/Zg8A/w8ADwAPAA8ADwAPAA8ADwD/DwAPAA8ADwAPAA8ADwAPAP8PAA8ADwAPAA8ADwAPAA8A/w8ADwAPAA8ADwAPAA8ADwD/DwAPAA8ADwAPAA8ADwAPAAcPAA8ABACosAIAKgeJUE5HDQoEGgpAAQ1JSERSCAAAAUABAQAIBgHAAFxyqGYAAAIAW0lEQVR42u0E1DFgAwjDsIF/AM9gAAckEnq0ACaZAC+1BGAAgIABAAYAGAAfAf8fAQEBvwQfAS8FzwGPAI8A/48ALwWPAI8AjwCPAD8BjwD/jwCPAC8FzwGPAI8AjwAvBQ+PAI8AjwCEAHBZrfZAA/7wb0jlsShJAEVORK5CYII='
	$Full_redico = _WinAPI_Base64Decode($Full_redico)
	Local $tSource = DllStructCreate('byte[' & BinaryLen($Full_redico) & ']')
	DllStructSetData($tSource, 1, $Full_redico)
	Local $tDecompress
	_WinAPI_LZNTDecompress($tSource, $tDecompress, 6594)
	$tSource = 0
	Local Const $bString = Binary(DllStructGetData($tDecompress, 1))
	If $bSaveBinary Then
		Local Const $hFile = FileOpen($sSavePath & "\Full_red.ico", 18)
		If @error Then Return SetError(1, 0, 0)
		FileWrite($hFile, $bString)
		FileClose($hFile)
	EndIf
	Return $bString
EndFunc   ;==>_Full_redico

Func _Full_yellowico($bSaveBinary = False, $sSavePath = @ScriptDir)
	Local $Full_yellowico
	$Full_yellowico &= 'ubEAAAABAAYAEBACEABwBAAoAQAAQGYAAAAYGAN46CUAeI4ADCAgBDwCAIAAdgMAADAwAzwgaAYAAF4ABkBAQQQeCgAAxgwAgAAFAx6UAF4uFwAAKJ8CIgCOAAYBLhYA//8XG+vgAIGTGIABMP+TPwA/AN8/AD8APwDUecHCQP95PwD/HwAfAB8AHwAfAB8AHwAfAP8fAB8AHwAfAB8AHwAfAB8A9x8A+lxhmWD/XJ8JHwAfAP8fAB8AHwAfAB8AHwAfAB8A/x8ADwAPAA8ADwAPAA8ADwD/DwAPAA8ADwAPAA8ADwAPAP8PAA8ADwAPAA8ADwAPAA8A/w8ADwAPAA8ADwAPAA8ADwD/DwAPAA8ADwAPAA8ADwAPAP8PAA8ADwAPAA8ADwAPAA8A/w8ADwAPAA8ADwAPAA8ADwD/DwAPAA8ADwAPAA8ADwAPAN8PAA8ADwByZrGUgH9mf2b/DwAPAA8ADwAPAA8ADwAPAP8PAA8ADwAPAA8ADwAPAA8A/w8ADwAPAA8ADwAPAA8ADwD/DwAPAA8ADwAPAA8ADwAPAP8PAA8ADwAPAA8ADwAPAA8ADw8ADwAPAAQAqLACACoHiVBORw0KBBoKQAENSUhEUggAAAFAAQEACAYBwABccqhmAAACAFtJREFUeNrtBNQxYAMIwzDAvwDnYQAHJBJ6tACTSgEvjQRgAICAAQAGABgAHwH/HwEBAb8EHwEvBc8BjwCPAP+PAC8FjwCPAI8AjwA/AY8A/48AjwAvBc8BjwCPAI8ALwUPjwCPAI8AhABwWebLQAT9ygltGbEoSQBFTkSuQmCC'
	$Full_yellowico = _WinAPI_Base64Decode($Full_yellowico)
	Local $tSource = DllStructCreate('byte[' & BinaryLen($Full_yellowico) & ']')
	DllStructSetData($tSource, 1, $Full_yellowico)
	Local $tDecompress
	_WinAPI_LZNTDecompress($tSource, $tDecompress, 6594)
	$tSource = 0
	Local Const $bString = Binary(DllStructGetData($tDecompress, 1))
	If $bSaveBinary Then
		Local Const $hFile = FileOpen($sSavePath & "\Full_yellow.ico", 18)
		If @error Then Return SetError(1, 0, 0)
		FileWrite($hFile, $bString)
		FileClose($hFile)
	EndIf
	Return $bString
EndFunc   ;==>_Full_yellowico

; ######################################################################################################################################################################################################

Func _WinAPI_Base64Decode($sB64String)
	Local $aCrypt = DllCall("Crypt32.dll", "bool", "CryptStringToBinaryA", "str", $sB64String, "dword", 0, "dword", 1, "ptr", 0, "dword*", 0, "ptr", 0, "ptr", 0)
	If @error Or Not $aCrypt[0] Then Return SetError(1, 0, "")
	Local $bBuffer = DllStructCreate("byte[" & $aCrypt[5] & "]")
	$aCrypt = DllCall("Crypt32.dll", "bool", "CryptStringToBinaryA", "str", $sB64String, "dword", 0, "dword", 1, "struct*", $bBuffer, "dword*", $aCrypt[5], "ptr", 0, "ptr", 0)
	If @error Or Not $aCrypt[0] Then Return SetError(2, 0, "")
	Return DllStructGetData($bBuffer, 1)
EndFunc   ;==>_WinAPI_Base64Decode

Func _WinAPI_LZNTDecompress(ByRef $tInput, ByRef $tOutput, $iBufferSize)
	$tOutput = DllStructCreate("byte[" & $iBufferSize & "]")
	If @error Then Return SetError(1, 0, 0)
	Local $aRet = DllCall("ntdll.dll", "uint", "RtlDecompressBuffer", "ushort", 0x0002, "struct*", $tOutput, "ulong", $iBufferSize, "struct*", $tInput, "ulong", DllStructGetSize($tInput), "ulong*", 0)
	If @error Then Return SetError(2, 0, 0)
	If $aRet[0] Then Return SetError(3, $aRet[0], 0)
	Return $aRet[6]
EndFunc   ;==>_WinAPI_LZNTDecompress